{% set name = "jsbeautifier" %}
{% set version = "1.14.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsbeautifier-{{ version }}.tar.gz
  sha256: d4c4e263a42dd6194afb9dbe54710be3c5604492cbec3e89c92dd98513f98b9f

build:
  number: 0
  noarch: python
  entry_points:
    - js-beautify = jsbeautifier:main
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - editorconfig >=0.12.2
    - python >=3.6
    - six >=1.13.0

test:
  imports:
    - jsbeautifier
    - jsbeautifier.cli
  commands:
    - pip check
    - js-beautify --help
  requires:
    - pip

about:
  home: https://beautifier.io
  summary: JavaScript unobfuscator and beautifier.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mitchellwood
    - fhoehle
    - whophil
