{% set name = "jsbeautifier" %}
{% set version = "1.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jsbeautifier-{{ version }}.tar.gz
  sha256: ebd733b560704c602d744eafc839db60a1ee9326e30a2a80c4adb8718adc1b24

build:
  number: 1
  noarch: python
  entry_points:
    - js-beautify = jsbeautifier:main
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
  run:
    - editorconfig >=0.12.2
    - python >={{ python_min }}
    - six >=1.13.0

test:
  imports:
    - jsbeautifier
    - jsbeautifier.cli
  commands:
    - pip check
    - js-beautify --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://beautifier.io
  summary: JavaScript unobfuscator and beautifier.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mitchellwood
    - fhoehle
    - whophil
